param(
    [string]$Version = "2.1.0-rc1",
    [switch]$SkipInstaller,
    [switch]$AllowBlockedStartupTest
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Python = Join-Path $Root ".venv\Scripts\python.exe"
$BuildDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd")

if (-not (Test-Path $Python)) {
    throw "Python environment not found: $Python"
}

Push-Location $Root
try {
    & $Python -m pytest -q
    if ($LASTEXITCODE -ne 0) { throw "Canonical test suite failed." }

    @"
`"`"`"Release metadata generated by build_release.ps1.`"`"`"

APP_VERSION = `"$Version`"
BUILD_DATE = `"$BuildDate`"
"@ | Set-Content -Path (Join-Path $Root "build_info.py") -Encoding ascii

    & $Python (Join-Path $Root "tools\generate_icon.py")
    if ($LASTEXITCODE -ne 0) { throw "Icon generation failed." }

    & $Python -m PyInstaller --clean --noconfirm (Join-Path $Root "GenealogyDB.spec")
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller build failed." }

    $SmokeHome = Join-Path $env:TEMP ("GenealogyDB-smoke-" + [guid]::NewGuid().ToString("N"))
    $PreviousHome = $env:GENEALOGYDB_HOME
    $StartupStatus = "passed"
    try {
        $env:GENEALOGYDB_HOME = $SmokeHome
        try {
            $Process = Start-Process -FilePath (Join-Path $Root "dist\GenealogyDB.exe") -ArgumentList "--smoke-test" -PassThru -Wait
        }
        catch {
            if (-not $AllowBlockedStartupTest) { throw }
            $StartupStatus = "blocked by Windows Application Control"
            Write-Warning "Packaged startup test was blocked by system application policy."
        }
        if ($StartupStatus -ne "passed") { $Process = $null }
        if ($Process -and $Process.ExitCode -ne 0) { throw "Packaged startup test failed with exit code $($Process.ExitCode)." }
        if ($Process) {
            foreach ($Directory in @("data", "backups", "exports", "logs", "plugins")) {
                if (-not (Test-Path (Join-Path $SmokeHome $Directory))) { throw "Startup test did not create $Directory/." }
            }
            if (-not (Test-Path (Join-Path $SmokeHome "data\genealogy.db"))) { throw "Startup test did not initialize genealogy.db." }
        }
    }
    finally {
        $env:GENEALOGYDB_HOME = $PreviousHome
        Remove-Item -Recurse -Force $SmokeHome -ErrorAction SilentlyContinue
    }

    $Executable = Get-Item (Join-Path $Root "dist\GenealogyDB.exe")
    Write-Host ("Executable: {0:N2} MB" -f ($Executable.Length / 1MB))

    if (-not $SkipInstaller) {
        $Candidates = @(
            "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe",
            "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
            "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
        )
        $Iscc = $Candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
        if (-not $Iscc) { throw "Inno Setup 6 was not found. Install it or rerun with -SkipInstaller." }
        & $Iscc "/DMyAppVersion=$Version" (Join-Path $Root "installer\GenealogyDB.iss")
        if ($LASTEXITCODE -ne 0) { throw "Installer build failed." }
        $Installer = Get-Item (Join-Path $Root "release\GenealogyDB-$Version-Setup.exe")
        Write-Host ("Installer: {0:N2} MB" -f ($Installer.Length / 1MB))
    }

    Write-Host "Startup test: $StartupStatus"
}
finally {
    Pop-Location
}